apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "readeruser" to read pods in the "default" namespace.
# We have a Role named "reader-role" in the namespace.
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
# Affected users:
- kind: User
  name: readeruser # case sensitive name of user that the role is applied to
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: reader-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io