# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv-volume
#   labels:
#     type: local
#     app: db
# spec:
#   storageClassName: microk8s-hostpath
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/opt/db/data"
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: postgres-pv-claim
#   labels:
#     app: db
# spec:
#   storageClassName: microk8s-hostpath
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---      
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: microk8s-hostpath
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none