apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
spec:
  tls:
  - secretName: my-tls-secret
  rules:
  - host: sc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inventory-ui-service
            port:
              number: 8091
