apiVersion: v1
kind: Service
metadata:
  name: inventory-ui-service
  labels:
    {{- include "helm_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm_chart.selectorLabels" . | nindent 4 }}
